### Contexto e Objetivo

Está sendo desenvolvido um modelo de classificação de dados em uma base de serviço para avaliar se um cliente irá continuar no serviço ou irá cancelá-lo. Essa analise poderá ser util para identificar as chances do cliente querer desistir do serviço que possui, e avaliar os fatores que podem afetar nessa decisão

Importação de Dependências

In [51]:
import pandas as pd
import numpy as np 

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix
import xgboost as xgb


pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.precision', 2)

In [11]:
df_credit = pd.read_csv(r"..\\documents\\Credit_Card_Churn.csv")

# Análise Inicial da base de Crédito

In [12]:
df_credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10000 non-null  int64
 1   Attrition_Flag            10000 non-null  object
 2   Customer_Age              10000 non-null  int64
 3   Gender                    10000 non-null  object
 4   Dependent_count           10000 non-null  int64
 5   Education_Level           10000 non-null  object
 6   Marital_Status            10000 non-null  object
 7   Income_Category           10000 non-null  object
 8   Card_Category             10000 non-null  object
 9   Months_on_book            10000 non-null  int64
 10  Total_Relationship_Count  10000 non-null  int64
 11  Months_Inactive_12_mon    10000 non-null  int64
 12  Contacts_Count_12_mon     10000 non-null  int64
 13  Credit_Limit              10000 non-null  float64
 14  Total_Revolving_Bal       10000 non-null  float64
 15  Avg_Open_To_Buy           10000 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10000 non-null  float64
 17  Total_Trans_Amt           10000 non-null  int64
 18  Total_Trans_Ct            10000 non-null  int64
 19  Total_Ct_Chng_Q4_Q1       10000 non-null  float64
 20  Avg_Utilization_Ratio     10000 non-null  float64
dtypes: float64(6), int64(9), object(6)
memory usage: 1.6+ MB

Análise de valores únicos

In [13]:
for x in df_credit.columns:
    print(f'Coluna: {x}')
    print(np.sort(df_credit[x].unique()), "\n")

Coluna: CLIENTNUM
[100000000 100000001 100000002 ... 100009997 100009998 100009999]

Coluna: Attrition_Flag
['Attrited Customer' 'Existing Customer']

Coluna: Customer_Age
[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72]

Coluna: Gender
['F' 'M']

Coluna: Dependent_count
[0 1 2 3 4 5]

Coluna: Education_Level
['College' 'Doctorate' 'Graduate' 'High School' 'Post-Graduate'
 'Uneducated']

Coluna: Marital_Status
['Divorced' 'Married' 'Single']

Coluna: Income_Category
['$120K +' '$40K - $60K' '$60K - $80K' '$80K - $120K' 'Less than $40K'
 'Unknown']

Coluna: Card_Category
['Blue' 'Gold' 'Platinum' 'Silver']

Coluna: Months_on_book
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60]

Coluna: Total_Relationship_Count
[1 2 3 4 5 6]

Coluna: Months_Inactive_12_mon
[0 1 2 3 4 5 6]

Coluna: Contacts_Count_12_mon
[0 1 2 3 4 5 6]

Coluna: Credit_Limit
[ 1003.43  1004.38  1006.13 ... 34991.64 34993.07 34999.73]

Coluna: Total_Revolving_Bal
[7.00000e-02 2.40000e-01 3.50000e-01 ... 2.49907e+03 2.49966e+03
 2.49994e+03]

Coluna: Avg_Open_To_Buy
[-1386.8  -1305.96 -1296.12 ... 34705.25 34716.03 34974.31]

Coluna: Total_Amt_Chng_Q4_Q1
[0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3  0.31 0.32 0.33
 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47
 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6  0.61
 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89
 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.   1.01 1.02 1.03
 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13 1.14 1.15 1.16 1.17
 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27 1.28 1.29 1.3  1.31
 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41 1.42 1.43 1.44 1.45
 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55 1.56 1.57 1.58 1.59
 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69 1.7  1.71 1.72 1.73
 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83 1.84 1.85 1.86 1.87
 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97 1.98 1.99 2.   2.01
 2.02 2.03 2.04 2.05 2.06 2.07 2.08 2.09 2.1  2.11 2.12 2.13 2.14 2.15
 2.16 2.17 2.18 2.19 2.2  2.21 2.22 2.23 2.24 2.25 2.26 2.27 2.28 2.29
 2.3  2.31 2.32 2.33 2.34 2.35 2.36 2.37 2.38 2.39 2.4  2.41 2.42 2.43
 2.44 2.45 2.46 2.47 2.48 2.49 2.5  2.51 2.52 2.53 2.54 2.55 2.56 2.57
 2.58 2.59 2.6  2.61 2.62 2.63 2.64 2.65 2.66 2.67 2.68 2.69 2.7  2.71
 2.72 2.73 2.74 2.75 2.76 2.77 2.78 2.79 2.8  2.81 2.82 2.83 2.84 2.85
 2.86 2.87 2.88 2.89 2.9  2.91 2.92 2.93 2.94 2.95 2.96 2.97 2.98 2.99
 3.  ]

Coluna: Total_Trans_Amt
[  505   507   509 ... 19980 19981 19983]

Coluna: Total_Trans_Ct
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

Coluna: Total_Ct_Chng_Q4_Q1
[0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3  0.31 0.32 0.33
 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47
 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6  0.61
 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89
 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.   1.01 1.02 1.03
 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13 1.14 1.15 1.16 1.17
 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27 1.28 1.29 1.3  1.31
 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41 1.42 1.43 1.44 1.45
 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55 1.56 1.57 1.58 1.59
 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69 1.7  1.71 1.72 1.73
 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83 1.84 1.85 1.86 1.87
 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97 1.98 1.99 2.   2.01
 2.02 2.03 2.04 2.05 2.06 2.07 2.08 2.09 2.1  2.11 2.12 2.13 2.14 2.15
 2.16 2.17 2.18 2.19 2.2  2.21 2.22 2.23 2.24 2.25 2.26 2.27 2.28 2.29
 2.3  2.31 2.32 2.33 2.34 2.35 2.36 2.37 2.38 2.39 2.4  2.41 2.42 2.43
 2.44 2.45 2.46 2.47 2.48 2.49 2.5  2.51 2.52 2.53 2.54 2.55 2.56 2.57
 2.58 2.59 2.6  2.61 2.62 2.63 2.64 2.65 2.66 2.67 2.68 2.69 2.7  2.71
 2.72 2.73 2.74 2.75 2.76 2.77 2.78 2.79 2.8  2.81 2.82 2.83 2.84 2.85
 2.86 2.87 2.88 2.89 2.9  2.91 2.92 2.93 2.94 2.95 2.96 2.97 2.98 2.99
 3.  ]

Coluna: Avg_Utilization_Ratio
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.14 1.15
 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.27 1.28 1.3  1.31
 1.32 1.33 1.34 1.36 1.37 1.38 1.4  1.41 1.42 1.43 1.44 1.45 1.46 1.47
 1.48 1.49 1.51 1.52 1.53 1.54 1.55 1.56 1.58 1.61 1.62 1.63 1.64 1.65
 1.67 1.68 1.69 1.72 1.73 1.77 1.81 1.88 1.9  1.98 2.05 2.08 2.1  2.11
 2.18 2.21 2.33]

Avaliar se nos valores numericos apresentam valores abaixo de 0

In [17]:
[c  for c in df_credit.columns if df_credit[c].dtype != 'object']

['CLIENTNUM',
 'Customer_Age',
 'Dependent_count',
 'Months_on_book',
 'Total_Relationship_Count',
 'Months_Inactive_12_mon',
 'Contacts_Count_12_mon',
 'Credit_Limit',
 'Total_Revolving_Bal',
 'Avg_Open_To_Buy',
 'Total_Amt_Chng_Q4_Q1',
 'Total_Trans_Amt',
 'Total_Trans_Ct',
 'Total_Ct_Chng_Q4_Q1',
 'Avg_Utilization_Ratio']

In [24]:
colunas_numericas = [c  for c in df_credit.columns if df_credit[c].dtype != 'object']

print("Colunas com valores abaixo de 0:\n")

for c in colunas_numericas:
    if (df_credit[c] < 0).any():
        print(c)

Colunas com valores abaixo de 0:

Avg_Open_To_Buy

In [25]:
# Análise percentual de clientes inexistentes

df_credit['Attrition_Flag'].value_counts(normalize=True)

Attrition_Flag
Existing Customer    0.85
Attrited Customer    0.15
Name: proportion, dtype: float64

Adaptação dos Dados

In [ ]:
# Nessa etapa será adaptada as colunas string que serão testadas nos modelos

df_base_credit = df_credit.copy()

income_category_map = {"Unknown": 0, "Less than $40K": 1, "$40K - $60K": 2,
                       "$60K - $80K": 3, "$80K - $120K": 4, "$120K +": 5}

education_map = {
       'Uneducated': 0, 'High School': 1, 'College': 2,
       'Graduate': 3, 'Post-Graduate': 4, 'Doctorate': 5 
}

atrition_flag_map = {
    'Existing Customer': 1,
    'Attrited Customer': 0
}

df_base_credit['Is_Male'] = df_base_credit['Gender'].map(lambda x: x == 'M').astype("int")
df_base_credit['Is_Female'] = df_base_credit['Gender'].map(lambda x: x == 'F').astype("int")

df_base_credit['Attrition_Flag'] = df_base_credit['Attrition_Flag'].map(
                                                    lambda x: atrition_flag_map[x]
                                                ).astype("int")

df_base_credit['Income_Category'] = df_base_credit['Income_Category'].map(
                                                    lambda x: income_category_map[x]
                                                ).astype("int")

df_base_credit['Education_Level'] = df_base_credit['Education_Level'].map(
                                                    lambda x: education_map[x]
                                                ).astype("int")

df_base_credit['Status_Divorced'] = df_base_credit['Marital_Status'].map(lambda x: x == 'Divorced').astype("int")
df_base_credit['Status_Single'] = df_base_credit['Marital_Status'].map(lambda x: x == 'Single').astype("int")
df_base_credit['Status_Married'] = df_base_credit['Marital_Status'].map(lambda x: x == 'Married').astype("int")

df_base_credit['Is_Blue_Card'] = df_base_credit['Card_Category'].map(lambda x: x == 'Blue').astype("int")
df_base_credit['Is_Silver_Card'] = df_base_credit['Card_Category'].map(lambda x: x == 'Silver').astype("int")
df_base_credit['Is_Gold_Card'] = df_base_credit['Card_Category'].map(lambda x: x == 'Gold').astype("int")
df_base_credit['Is_Platinum_Card'] = df_base_credit['Card_Category'].map(lambda x: x == 'Platinum').astype("int")


# A coluna CLIENTNUM será removida pois apresenta valores repetidos, 
# e então atrapalhando na classificação dos dados

df_base_credit = df_base_credit.drop(columns=['CLIENTNUM', 'Gender', 'Marital_Status', 'Card_Category'])

df_base_credit

,Attrition_Flag,Customer_Age,Dependent_count,Education_Level,Income_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Is_Male,Is_Female,Status_Divorced,Status_Single,Status_Married,Is_Blue_Card,Is_Silver_Card,Is_Gold_Card,Is_Platinum_Card
0,1,57,0,0,2,51,1,2,6,3206.56,1878.94,1327.62,1.07,13740,34,2.09,0.59,0,1,1,0,0,1,0,0,0
1,0,61,3,4,2,19,2,2,6,5134.84,2498.54,2636.30,2.65,14279,64,0.61,0.49,0,1,0,1,0,0,1,0,0
2,1,62,0,1,1,31,2,6,3,20704.64,1581.42,19123.22,2.00,19353,41,1.36,0.08,0,1,1,0,0,1,0,0,0
3,1,39,3,5,3,20,5,0,5,28157.67,552.70,27604.97,2.56,18360,123,0.71,0.02,1,0,0,0,1,1,0,0,0
4,1,52,3,3,5,24,1,5,0,27955.43,1430.73,26524.70,0.60,1205,69,0.46,0.05,0,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,33,1,4,2,42,2,1,3,14118.49,1608.60,12509.89,1.33,12270,76,2.71,0.11,0,1,0,1,0,1,0,0,0
9996,0,69,3,5,3,39,6,0,5,1489.53,2139.22,-649.69,1.33,9976,20,1.19,1.44,1,0,0,0,1,1,0,0,0
9997,0,46,2,0,3,49,1,3,0,18717.68,398.80,18318.88,1.09,4585,43,0.57,0.02,1,0,1,0,0,1,0,0,0
9998,1,33,3,3,5,16,5,3,1,24765.71,942.11,23823.60,2.44,17092,54,0.85,0.04,1,0,0,1,0,1,0,0,0
9999,1,53,0,3,3,48,5,5,3,20634.90,2300.76,18334.14,1.71,889,140,2.37,0.11,1,0,0,1,0,1,0,0,0

In [ ]:
df_base_credit[['']]

Definição das variáveis de treino e teste

In [37]:
X = df_base_credit.drop(columns=['Attrition_Flag'])
y = df_base_credit['Attrition_Flag']

# Será dividido os dados dos eixos x e y em 80% de treino e 20% de teste
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

# Modelo de Regressão Logística

In [53]:
# Modelo Logistic Regression
logistic_regression = LogisticRegression()
logistic_regression.fit(X_train, Y_train)

# Obtenção de Probabilidades (importante para o Gini), 
# Será pego a probabilidade de Churn (classe 1)
prob_lr = logistic_regression.predict_proba(X_test)[:, 1]

logistic_regression.score(X_train, Y_train)

c:\Users\rpf97\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8455

In [50]:
# Calculo da Curva de Lorenz e Coeviciente de Gini

# o coeficiente de gini do modelo é baixo
auc = roc_auc_score(Y_test, prob_lr)
gini = 2 * auc - 1

print(f'O Coeficiente de Gini desse modelo é {gini}')

O Coeficiente de Gini desse modelo é -0.03493396984375852

In [52]:
# Matriz de Conversão (usado para prever as saídas reais e previstes)

confusion_matrix(y, logistic_regression.predict(X))

array([[   0, 1538],
       [   0, 8462]])

In [55]:
# Análise de quais colunas estão afetando o Modelo

pd.DataFrame({
    'Coluna': X_train.columns,
    'Coeficiente': logistic_regression.coef_[0]   
}).sort_values(by='Coeficiente', ascending=True)

                      Coluna  Coeficiente
3            Income_Category    -4.29e-03
10           Avg_Open_To_Buy    -1.20e-05
8               Credit_Limit     1.35e-05
12           Total_Trans_Amt     2.19e-05
9        Total_Revolving_Bal     2.55e-05
22            Is_Silver_Card     6.07e-04
18           Status_Divorced     9.90e-04
13            Total_Trans_Ct     1.59e-03
16                   Is_Male     1.60e-03
23              Is_Gold_Card     1.62e-03
24          Is_Platinum_Card     1.88e-03
20            Status_Married     2.14e-03
15     Avg_Utilization_Ratio     3.20e-03
21              Is_Blue_Card     6.62e-03
4             Months_on_book     6.72e-03
19             Status_Single     7.59e-03
1            Dependent_count     8.82e-03
17                 Is_Female     9.12e-03
0               Customer_Age     1.13e-02
14       Total_Ct_Chng_Q4_Q1     1.56e-02
6     Months_Inactive_12_mon     1.57e-02
11      Total_Amt_Chng_Q4_Q1     1.94e-02
2            Education_Level     2.17e-02
5   Total_Relationship_Count     3.98e-02
7      Contacts_Count_12_mon     4.52e-02

# Random Florest

In [16]:
# Modelo Random Florest
random_florest = RandomForestClassifier()
random_florest.fit(X_train, Y_train)

prob_rf = random_florest.predict_proba(X_test)[:, 1]
prob_rf

array([0.78, 0.81, 0.84, ..., 0.84, 0.88, 0.74], shape=(3000,))

# XGBOOT

In [ ]:
#xgboot_classifier = xgb.XGBClassifier(n_estimators=100, max_depth=3, learning_rate=0.1) 

#xgboot_classifier.fit(X_train, Y_train)

#prob_xgb = xgboot_classifier.predict_proba(X_test)[:, 1]
#prob_xgb

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got ['Attrited Customer' 'Existing Customer']